#version: '3.8'
#
#services:
#  postgres:
#    image: postgres:15-alpine
#    container_name: wallet-postgres
#    environment:
#      POSTGRES_DB: wallet_db
#      POSTGRES_USER: wallet_user
#      POSTGRES_PASSWORD: wallet_pass
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U wallet_user"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  app:
#    build: .
#    container_name: wallet-app
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wallet_db
#      SPRING_DATASOURCE_USERNAME: wallet_user
#      SPRING_DATASOURCE_PASSWORD: wallet_pass
#      SPRING_JPA_HIBERNATE_DDL_AUTO: validate  # Liquibase управляет схемой
#      SPRING_LIQUIBASE_ENABLED: true          # ВКЛЮЧЕНО
#      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog/db.changelog-master.yaml
#    ports:
#      - "8080:8080"
#    restart: unless-stopped
#
#volumes:
#  postgres_data:
